# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PokerStreakChamps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokerStreakChamps-mobile
  pod 'Adjust','4.38.4'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
